// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmA1C0VbkNPRTUxZcL_0EqDS-ii5xyVB8',
    appId: '1:563083682756:web:4a4e13e2786e397848fa91',
    messagingSenderId: '563083682756',
    projectId: 'online-learning-erp',
    authDomain: 'online-learning-erp.firebaseapp.com',
    storageBucket: 'online-learning-erp.firebasestorage.app',
    measurementId: 'G-4RTH5CFHYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk52BGEfwEedXLno8jQVTwlCNHRssji24',
    appId: '1:563083682756:android:01f3fe93944341ae48fa91',
    messagingSenderId: '563083682756',
    projectId: 'online-learning-erp',
    storageBucket: 'online-learning-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPykPyFP-6m5NxW4gYvc8unOSApZ6WVM',
    appId: '1:563083682756:ios:ffca501092eef2b448fa91',
    messagingSenderId: '563083682756',
    projectId: 'online-learning-erp',
    storageBucket: 'online-learning-erp.firebasestorage.app',
    iosBundleId: 'com.example.onlineLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAPykPyFP-6m5NxW4gYvc8unOSApZ6WVM',
    appId: '1:563083682756:ios:ffca501092eef2b448fa91',
    messagingSenderId: '563083682756',
    projectId: 'online-learning-erp',
    storageBucket: 'online-learning-erp.firebasestorage.app',
    iosBundleId: 'com.example.onlineLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmA1C0VbkNPRTUxZcL_0EqDS-ii5xyVB8',
    appId: '1:563083682756:web:ac7fb1876e5cfe4c48fa91',
    messagingSenderId: '563083682756',
    projectId: 'online-learning-erp',
    authDomain: 'online-learning-erp.firebaseapp.com',
    storageBucket: 'online-learning-erp.firebasestorage.app',
    measurementId: 'G-GQ2QLBXB81',
  );
}
